services:

  pia:
    build: pia
    restart: on-failure
    cap_add:
      - NET_ADMIN # to create wireguard interface
      - SYS_MODULE # for wireguard module
    sysctls:
      # Wireguard requires this
      - "net.ipv4.conf.all.src_valid_mark=1"
      # Enable packet routing
      - "net.ipv4.ip_forward=1"
    privileged: true # current version of wireguard needs this
    networks:
      vpn:
        ipv4_address: 172.18.0.2
    env_file:
      - pia.env

  squid:
    ports:
      - "3128:3128"
    build: squid
    cap_add:
      - NET_ADMIN # to update default route
    dns_search: .
    dns: 10.0.0.243
    networks:
      - vpn
    restart: on-failure
    depends_on:
      - pia
    profiles:
      - disabled

  tor:
    ports:
      - "9050:9050"
    build: tor
    cap_add:
      - NET_ADMIN # to update default route
    dns_search: .
    dns: 10.0.0.243
    networks:
      - vpn
    restart: on-failure
    depends_on:
      - pia
    profiles:
      - disabled


networks:
  vpn:
    internal: false
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
